version: '1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: alok123
      MYSQL_DATABASE: hotel
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: alok123
      MYSQL_DB: hotel

volumes:
  db_data:
